import image_1 from "../../../../assets/images/CourseImages/BestSelling/1.jpg";
import image_2 from "../../../../assets/images/CourseImages/BestSelling/2.jpg";
import image_3 from "../../../../assets/images/CourseImages/BestSelling/3.jpg";
import image_4 from "../../../../assets/images/CourseImages/BestSelling/4.jpg";
import image_5 from "../../../../assets/images/CourseImages/BestSelling/5.jpg";
import image_6 from "../../../../assets/images/CourseImages/BestSelling/6.jpg";
import image_7 from "../../../../assets/images/CourseImages/BestSelling/7.jpg";
import image_8 from "../../../../assets/images/CourseImages/BestSelling/8.jpg";
import image_9 from "../../../../assets/images/CourseImages/BestSelling/9.jpg";
import image_10 from "../../../../assets/images/CourseImages/BestSelling/10.jpg";
import AuthorAvatar from "../../../../assets/images/CourseImages/BestSelling/AuthurAvatar.jpg";

export const coursesData = [
  {
    id: 1,
    image: image_1,
    title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
    price: 57,
    category: "Design",
    students: 265.7,
    rating: 4.9,
    categoryColor: "#23BD33",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 2,
    image: image_2,
    title: "The Complete 2021 Web Development Bootcamp",
    price: 39,
    category: "Development",
    students: 165.2,
    rating: 4.6,
    categoryColor: "#564FFD",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 3,
    image: image_3,
    title: "Learn Python Programming Masterclass",
    price: 85,
    category: "Business",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#E34444",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 4,
    image: image_4,
    title: "The Complete Digital Marketing Course - 12 Courses in 1",
    price: 39,
    category: "Marketing",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#882929",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 5,
    image: image_5,
    title: "Reiki Level I, II and Master/Teacher Program",
    price: 39,
    category: "IT & Software",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#993D20",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 6,
    image: image_6,
    title: "The Complete Foundation Stock Trading Course",
    price: 39,
    category: "Music",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#564FFD",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 7,
    image: image_7,
    title: "Beginner to Pro in Excel: Financial Modeling and Valuati...",
    price: 39,
    category: "IT & Software",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#23BD33",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 8,
    image: image_8,
    title: "The Python Mega Course: Build 10 Real World Applications",
    price: 39,
    category: "IT & Software",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#FF6636",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 9,
    image: image_9,
    title: "Copywriting - Become a Freelance Copywriter, your ow...",
    price: 39,
    category: "Design",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#564FFD",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
  {
    id: 10,
    image: image_10,
    title: "Google Analytics Certification - Learn How To Pass The Exam",
    price: 39,
    category: "Lifestyle",
    students: 265.7,
    rating: 4.6,
    categoryColor: "#FF6636",
    authorAvatar: AuthorAvatar,
    authorName: "Kevin Gilbert",
    level: "Begginer",
    duration: 13,
  },
];
